# Generated by Django 3.2.6 on 2021-08-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstrackerapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
