# Generated by Django 3.2.6 on 2021-08-19 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newstrackerapi', '0002_auto_20210819_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default=datetime.datetime(2021, 8, 19, 1, 37, 36, 907329, tzinfo=utc), max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
