# Generated by Django 3.2.6 on 2021-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstrackerapi', '0003_auto_20210819_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
